name: pressable
description: Touch effects to your widgets for ripple, scale, opacity, fill, and custom effects.
version: 0.10.0
homepage: https://github.com/vaetas/pressable
repository: https://github.com/vaetas/pressable

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
