name: pressable
description: Add various touch effects to your widgets. Supports ripple, scale, opacity, fill, and custom builder.
version: 0.2.0
homepage: https://github.com/vaetas/pressable

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
