name: pressable
description: Touch effects to your widgets for ripple, scale, opacity, fill, and custom effects.
version: 0.7.0
homepage: https://github.com/vaetas/pressable

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8

flutter:
  uses-material-design: true
