name: pressable
description: Add various touch effects to your widgets. Supports ripple, scale, opacity, fill, and custom builder.
version: 0.3.1
homepage: https://github.com/vaetas/pressable

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0

flutter:
